### ISSUE TITLE
Peer to peer code review - Week 4

### ISSUE THREAD

**Issue by estebanmual** [VicPeralta/Portfolio#21]
Hi Victor, your code actually looks amazing! 

We want to highlight your excellent work in the next functions: 
- When you click on the hamburger icon the scroll feature works correctly.
- The way that you linked your JavaScript at the top of the HTML script using defer.
- The way that you order your JavaScript file was also amazing!

**Comment by jpol01** [comment]
## Amazing!!
 >Flawless, I don't have anything to add you though in everything, thanks for sharing. :smile_cat:  :+1:

**Comment by VicPeralta** [comment]
Thank you for your comments.
